// src/features/home/components/Layout.tsx
import Header from "./Header.tsx";

function Layout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <section className="w-screen h-screen flex flex-col text-center">
                <Header />
                <div className="h-full flex flex-col gap-18 justify-center items-center">
                    {children}
                </div>
            </section>
        </>
    );
}

export default Layout;

// src/modules/authentication/components/Layout.vue
<script setup lang="ts">
import Header from "./Header.vue";
</script>

<template>
    <section class="w-screen h-screen flex flex-col text-center">
        <AuthHeader />
        <div class="h-full flex flex-col gap-4 justify-center items-center">
            <slot></slot>
        </div>
    </section>
</template>
